### PR TITLE
Implement UnixDatagram::new()

### PR DESCRIPTION
**Pull request by tailhook**
Datagram sockets may be created without being `bind`'ed. Then you can use
`send_to` to send data throught the socket.

In fact it's even possible to create a `connect()`'ed datagram socket. But I'm not sure what the API should be? Should socket have both `send` and `send_to`? Should it have `Write` trait instead? Should there be two classes: `UnixDatagram` and `UnixDatagramConnected`, so that latter only have `send` API. Thoughts?

### CODE REVIEW

**Comment by tailhook** [comment]
Hm, sorry for not providing tests yet.

When writing a test I've noticed that `recv_from` for anonymous connections does not return valid AF_UNIX addresss. What I see in `strace`:

```
recvfrom(3, "hello world", 11, 0, {sa_family=AF_UNSPEC, sa_data="\0\0\0\0\0\0\0\0\0\0\0\0\0\0"}, [0]) = 11
```

Which crashes with:

```
thread 'test::test_unnamed_unix_datagram' panicked at 'file descriptor did not correspond to a Unix socket', src/lib.rs:1061
```

So the question is: should I remove this check or change `recv_from` API to return `Option<SocketAddr>` ?

**Comment by sfackler** [comment]
The check should definitely be there or we'll be returning bogus address info. I think updating the API to return an `Option<SocketAddr>` probably makes the most sense.

**Comment by sfackler** [comment]
As far as the connected socket goes, there is a crate that provides a wrapper type for connected `UdpSockets` here: https://crates.io/crates/connected_socket. It might make sense to update that to support wrapping `UnixDatagram`s as well.

**Comment by tailhook** [comment]
> The check should definitely be there or we'll be returning bogus address info. I think updating the API to return an Option<SocketAddr> probably makes the most sense.

Well, I've done that. But if I get `local_addr` from such unnamed socket, I get `SocketAddr` with `AddressKind` of `Unnamed` so it may be a better choice (however `getsockname` returns zero-length `AF_UNIX` address, instead of `AF_UNSPEC` like `recvfrom`, so current implementation is consistent with linux internals, just might be not too user-friendly).

**Comment by sfackler** [comment]
Oh, interesting. How about we treat `AF_UNSPEC` as `Unnamed` always instead then? I just want to make sure we are only trying to read out of the data portion of the sockaddr if we know it's `AF_UNIX`. That'll let us avoid changing the signature of `recv_from`. Sorry for going back and forth on this!

**Comment by tailhook** [comment]
No problem, especially that previous commit had a stupid mistake :)

In fact it did not return AF_UNSPEC, it returned zero-length address, which was not checked for. I've added a check for returning at least size of family type returned before checking family itself.

**Comment by sfackler** [comment]
Thanks!

**Pull request merged**
